server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0

---

spring:
    profiles: development

---

spring:
    profiles: production
