server:
  port: 8031

spring:
  data:
    mongodb:
      host: mongodb
      port: 27018
      database: widgets

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

logging:
  file: user-service.log
  level: DEBUG

---

spring:
    profiles: local
    data:
      mongodb:
        host: localhost
        port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
    profiles: development

---

spring:
    profiles: production

logging:
  level: WARN

server:
    port: 0
