server:
  port: ${PORT:8031}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:127.0.0.1}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:users}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

---

spring:
    profiles: development

---

spring:
    profiles: production

server:
    port: 0
