server:
  port: 8031
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:127.0.0.1}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:user-development}

---

spring:
    profiles: development

---

spring:
    profiles: production
    data:
      mongodb:
        host: ${MONGO_HOST:127.0.0.1}
        port: ${MONGO_PORT:27017}
        database: ${MONGO_DB:user-production}
server:
    port: 0
