server:
  port: ${PORT:8030}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:127.0.0.1}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:widgets}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

logging:
  file: widget-service.log
  level: DEBUG

---

spring:
    profiles: development

---

spring:
    profiles: production

logging:
  level: WARN

server:
    port: 0
