server:
  port: 8030

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: widgets

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

logging:
  file: widget-service.log
  level:
    root: DEBUG

---

spring:
    profiles: local
    data:
      mongodb:
        host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
    profiles: development

---

spring:
    profiles: production

logging:
  level:
    root: WARN

server:
    port: 0
