server:
  port: 8030
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:127.0.0.1}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:widgets}

---

spring:
    profiles: development

---

spring:
    profiles: production
server:
    port: 0
